import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { CodeFile } from "./CodePanel";
import { buildRepoPath, normalizeRepoDirectory } from "@/lib/repoPath";
import { getGitHubToken, setGitHubToken } from "@/lib/tokenStorage";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  GitBranch,
  Plus,
  Loader2,
  Check,
  ExternalLink,
  Lock,
  Globe,
  FolderGit2,
} from "lucide-react";

interface GitHubRepo {
  id: number;
  name: string;
  full_name: string;
  private: boolean;
  html_url: string;
  default_branch: string;
}

interface PushToGitHubDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  files: CodeFile[];
  componentName: string;
}

const PushToGitHubDialog = ({
  open,
  onOpenChange,
  files,
  componentName,
}: PushToGitHubDialogProps) => {
  const [githubToken, setGithubToken] = useState("");
  const [repos, setRepos] = useState<GitHubRepo[]>([]);
  const [selectedRepo, setSelectedRepo] = useState<GitHubRepo | null>(null);
  const [loading, setLoading] = useState(false);
  const [pushing, setPushing] = useState(false);
  const [pushed, setPushed] = useState(false);
  const [commitUrl, setCommitUrl] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [tab, setTab] = useState<"existing" | "new">("existing");
  const [newRepoName, setNewRepoName] = useState("");
  const [isPrivate, setIsPrivate] = useState(true);
  const [username, setUsername] = useState("");
  const [commitMessage, setCommitMessage] = useState(
    `feat: add ${componentName} component`
  );
  const [directory, setDirectory] = useState("src/components");
  const isValidDirectory = Boolean(normalizeRepoDirectory(directory));

  useEffect(() => {
    const stored = getGitHubToken();
    if (stored) {
      setGithubToken(stored);
    }
  }, []);

  useEffect(() => {
    if (componentName) {
      setCommitMessage(`feat: add ${componentName} component`);
      setNewRepoName(componentName.toLowerCase().replace(/[^a-z0-9-]/g, "-"));
    }
  }, [componentName]);

  const fetchRepos = async (token: string) => {
    if (!supabase) {
      setError("Supabase is not configured. Add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to .env.local");
      return;
    }
    setLoading(true);
    setError(null);
    try {
      const { data, error: fnError } = await supabase.functions.invoke(
        "github-push?action=repos",
        {
          method: "GET",
          headers: { "x-github-token": token },
        }
      );
      if (fnError) throw fnError;
      setRepos(data || []);

      // Also fetch username
      const { data: userData } = await supabase.functions.invoke(
        "github-push?action=user",
        {
          method: "GET",
          headers: { "x-github-token": token },
        }
      );
      if (userData?.login) setUsername(userData.login);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : "Failed to fetch repos");
    } finally {
      setLoading(false);
    }
  };

  const handleConnectToken = () => {
    if (!githubToken.trim()) return;
    const token = githubToken.trim();
    setGitHubToken(token);
    fetchRepos(token);
  };

  const handlePush = async () => {
    if (!supabase) {
      setError("Supabase is not configured. Add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to .env.local");
      return;
    }
    setPushing(true);
    setError(null);
    setPushed(false);

    try {
      let owner = username;
      let repo = selectedRepo?.name || "";
      let branch = selectedRepo?.default_branch || "main";

      if (tab === "new") {
        if (!newRepoName.trim()) {
          setError("Repository name is required");
          setPushing(false);
          return;
        }
        // Create repo first
        const { data: newRepo, error: createError } =
          await supabase.functions.invoke("github-push?action=create-repo", {
            method: "POST",
            body: {
              githubToken: githubToken.trim(),
              repo: newRepoName.trim(),
              repoDescription: `${componentName} - Generated by Figma to Code`,
              isPrivate,
            },
          });
        if (createError) throw createError;
        owner = newRepo.owner?.login || username;
        repo = newRepo.name;
        branch = newRepo.default_branch || "main";

        // Wait a moment for GitHub to initialize the repo
        await new Promise((r) => setTimeout(r, 2000));
      }

      // Push files
      const filesToPush = files.map((f) => {
        const path = buildRepoPath(directory, f.name);
        if (!path) {
          throw new Error("Invalid target directory or file name.");
        }
        return {
          path,
          content: f.content,
        };
      });

      const { data: result, error: pushError } =
        await supabase.functions.invoke("github-push?action=push", {
          method: "POST",
          body: {
            githubToken: githubToken.trim(),
            owner,
            repo,
            branch,
            commitMessage,
            files: filesToPush,
          },
        });

      if (pushError) throw pushError;
      setPushed(true);
      setCommitUrl(
        result?.commitUrl ||
          `https://github.com/${owner}/${repo}`
      );
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : "Push failed");
    } finally {
      setPushing(false);
    }
  };

  const hasRepos = repos.length > 0 || username;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="bg-card border-border max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-foreground">
            <FolderGit2 className="w-5 h-5 text-primary" />
            Push to GitHub
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-4">
          {/* Token input */}
          {!hasRepos && (
            <div className="space-y-2">
              <label className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
                GitHub Personal Access Token
              </label>
              <p className="text-xs text-muted-foreground">
                Create a token at{" "}
                <a
                  href="https://github.com/settings/tokens/new?scopes=repo"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-primary hover:underline"
                >
                  github.com/settings/tokens
                </a>{" "}
                with <code className="text-xs font-mono bg-muted px-1 rounded">repo</code> scope.
              </p>
              <input
                type="password"
                value={githubToken}
                onChange={(e) => setGithubToken(e.target.value)}
                placeholder="ghp_..."
                className="w-full bg-muted border border-border rounded-lg px-3 py-2 text-sm font-mono text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
              />
              <button
                onClick={handleConnectToken}
                disabled={!githubToken.trim() || loading}
                className="w-full py-2 text-sm font-medium rounded-lg bg-primary text-primary-foreground hover:bg-primary/90 disabled:opacity-30 transition-colors flex items-center justify-center gap-2"
              >
                {loading ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <GitBranch className="w-4 h-4" />
                )}
                Connect to GitHub
              </button>
            </div>
          )}

          {error && (
            <div className="p-3 rounded-lg bg-destructive/10 border border-destructive/20">
              <p className="text-xs text-destructive">{error}</p>
            </div>
          )}

          {pushed && commitUrl && (
            <div className="p-4 rounded-lg bg-success/10 border border-success/20 text-center space-y-2">
              <Check className="w-8 h-8 text-success mx-auto" />
              <p className="text-sm font-medium text-foreground">
                Successfully pushed!
              </p>
              <a
                href={commitUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-1 text-xs text-primary hover:underline"
              >
                View on GitHub <ExternalLink className="w-3 h-3" />
              </a>
            </div>
          )}

          {hasRepos && !pushed && (
            <>
              {/* Tabs: Existing / New */}
              <div className="flex border-b border-border">
                <button
                  onClick={() => setTab("existing")}
                  className={`flex-1 py-2 text-xs font-medium border-b-2 transition-colors ${
                    tab === "existing"
                      ? "border-primary text-foreground"
                      : "border-transparent text-muted-foreground"
                  }`}
                >
                  Existing Repo
                </button>
                <button
                  onClick={() => setTab("new")}
                  className={`flex-1 py-2 text-xs font-medium border-b-2 transition-colors ${
                    tab === "new"
                      ? "border-primary text-foreground"
                      : "border-transparent text-muted-foreground"
                  }`}
                >
                  <Plus className="w-3 h-3 inline mr-1" />
                  New Repo
                </button>
              </div>

              {tab === "existing" && (
                <div className="space-y-2 max-h-40 overflow-y-auto">
                  {repos.map((repo) => (
                    <button
                      key={repo.id}
                      onClick={() => setSelectedRepo(repo)}
                      className={`w-full text-left px-3 py-2 rounded-lg text-sm flex items-center justify-between transition-colors ${
                        selectedRepo?.id === repo.id
                          ? "bg-primary/10 border border-primary/30"
                          : "bg-muted border border-transparent hover:border-border"
                      }`}
                    >
                      <span className="flex items-center gap-2 min-w-0">
                        {repo.private ? (
                          <Lock className="w-3 h-3 text-muted-foreground shrink-0" />
                        ) : (
                          <Globe className="w-3 h-3 text-muted-foreground shrink-0" />
                        )}
                        <span className="truncate text-foreground">
                          {repo.full_name}
                        </span>
                      </span>
                      {selectedRepo?.id === repo.id && (
                        <Check className="w-4 h-4 text-primary shrink-0" />
                      )}
                    </button>
                  ))}
                </div>
              )}

              {tab === "new" && (
                <div className="space-y-3">
                  <input
                    type="text"
                    value={newRepoName}
                    onChange={(e) => setNewRepoName(e.target.value)}
                    placeholder="repository-name"
                    className="w-full bg-muted border border-border rounded-lg px-3 py-2 text-sm font-mono text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
                  />
                  <label className="flex items-center gap-2 text-xs text-muted-foreground cursor-pointer">
                    <input
                      type="checkbox"
                      checked={isPrivate}
                      onChange={(e) => setIsPrivate(e.target.checked)}
                      className="rounded border-border"
                    />
                    Private repository
                  </label>
                </div>
              )}

              {/* Directory & commit message */}
              <div className="space-y-2">
                <label className="text-xs font-medium text-muted-foreground">
                  Directory
                </label>
                <input
                  type="text"
                  value={directory}
                  onChange={(e) => setDirectory(e.target.value)}
                  className="w-full bg-muted border border-border rounded-lg px-3 py-2 text-sm font-mono text-foreground focus:outline-none focus:ring-1 focus:ring-primary"
                />
                {!isValidDirectory && (
                  <p className="text-xs text-destructive">
                    Use a relative path with letters, numbers, `.`, `_`, `-`, and `/`.
                  </p>
                )}
              </div>

              <div className="space-y-2">
                <label className="text-xs font-medium text-muted-foreground">
                  Commit message
                </label>
                <input
                  type="text"
                  value={commitMessage}
                  onChange={(e) => setCommitMessage(e.target.value)}
                  className="w-full bg-muted border border-border rounded-lg px-3 py-2 text-sm text-foreground focus:outline-none focus:ring-1 focus:ring-primary"
                />
              </div>

              {/* File preview */}
              <div className="space-y-1">
                <label className="text-xs font-medium text-muted-foreground">
                  Files to push ({files.length})
                </label>
                <div className="bg-muted rounded-lg p-2 space-y-1 max-h-24 overflow-y-auto">
                  {files.map((f) => (
                    <div
                      key={f.name}
                      className="text-xs font-mono text-muted-foreground"
                    >
                      {directory}/{f.name}
                    </div>
                  ))}
                </div>
              </div>

              <button
                onClick={handlePush}
                disabled={
                  pushing ||
                  !isValidDirectory ||
                  (tab === "existing" && !selectedRepo) ||
                  (tab === "new" && !newRepoName.trim())
                }
                className="w-full py-2.5 text-sm font-medium rounded-lg bg-primary text-primary-foreground hover:bg-primary/90 disabled:opacity-30 transition-colors flex items-center justify-center gap-2"
              >
                {pushing ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <GitBranch className="w-4 h-4" />
                )}
                {pushing
                  ? "Pushing..."
                  : tab === "new"
                  ? "Create & Push"
                  : "Push to Repository"}
              </button>
            </>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default PushToGitHubDialog;
